### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by instruccionesaldorso** [dmitryd/typo3-realurl#669] opened 2019-08-07 09:39 UTC
Can the latest version of the extension be checked against PHP 7.3 compatibility?

https://github.com/dmitryd/typo3-realurl/blob/development/ext_emconf.php#L29
https://github.com/dmitryd/typo3-realurl/blob/development/composer.json#L28

**Comment by LeoniePhiline** [comment] 2019-09-19 17:59
@dmitryd We are using the extension for quite a while on PHP 7.3.
Please release a new version with adjusted restraints for 7.3 on packagist, so everyone can let go of the obnoxious `--ignore-platform-reqs`.

Thank you!

**Comment by instruccionesaldorso** [comment] 2019-11-25 16:53
Any update on this issue? The only extension with no PHP 7.3 restraint we have in our systems is this one.

**Comment by PowerKiKi** [comment] 2019-12-17 17:44
This is a duplicate of #657 and should be closed.

**Comment by dmitryd** [comment] 2019-12-20 11:45
There was a report in TYPO3 slack that somebody had problems with php 7.3 and regexp used in realurl.

**Comment by dmitryd** [comment] 2019-12-20 11:46
Merged the PR.

**Closed by dmitryd** 2019-12-20 11:46 UTC
