### ISSUE TITLE
URL not fetched from cache

### ISSUE THREAD

**Issue by hannesbochmann** [dmitryd/typo3-realurl#429] opened 2017-03-08 08:45 UTC
I have the following situation. Upon encoding the resulting speaking URL is written to cache. When there are additional query parameters without postvar configuration like ?tx_myext[item]=123 those parameters get urlencoded which leads to something like ?tx_myext%5Bitem%5D=123 in the cache. Upon on decoding the URL is fetched from the cache. But a this time the additional query parameters are not urlencoded which leads to a cache miss.
Is there a problem in realurl or in my application/environment?

P.S. The link is created with the fluid ViewHelper, so there shouldn't not be an error when creating the typolink.

**Comment by dmitryd** [comment] 2017-03-09 13:02
Duplicate of #414

**Closed by dmitryd** 2017-03-09 13:02 UTC
