### ISSUE TITLE
RealURL 2 does not use Title of localization

### ISSUE THREAD

**Issue by Luggi2** [dmitryd/typo3-realurl#202] opened 2016-07-19 15:14 UTC
Hi there,
since RealURL 2, the Title of the localization is not longer considdered in the URL.

I got 2 languages: DE (default) and EN. When I'm gonna open an EN URL the path looks like this: /de/realurl-default/
It should look like this "/de/realurl-english/" because the title of the page_language_overlay is "RealURL English"

It works in RealURL 1.9! But not longer in Version 2.
Thats my config:

TypoScript
`config {
    doctype = html_5
    metaCharset = utf-8
    renderCharset = utf-8

    # Absolute URLs
    absRefPrefix = /

    simulateStaticDocuments = 0

    tx_realurl_enable = 1
    sys_language_uid = 0
    language = de
    country = DE

    sys_language_mode = content_fallback
    sys_language_overlay = hideNonTranslated

    linkVars = LC
    uniqueLinkVars = 1

    lg_iso_2 = de
    cn_iso_2 = DE

    htmlTag_langKey = de
    disablePrefixComment = 1

    typolinkCheckRootline = 1
    typolinkEnableLinksAcrossDomains = 1

    contentObjectExceptionHandler = 0
}`

ReaLURL
`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] = array(
    '_DEFAULT' => array(
        'init' => array(
            'enableCHashCache' => true,
            'appendMissingSlash' => 'ifNotFile',
            'enableUrlDecodeCache' => true,
            'enableUrlEncodeCache' => true,
            'emptyUrlReturnValue' => '/',
        ),
        'pagePath' => array(
            'type' => 'user',
            'userFunc' =>
                'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
            'spaceCharacter' => '-',
            'languageGetVar' => 'L',
            'rootpage_id' => 1,
            'expireDays' => 7,
        ),
        'preVars' => array(
            array(
                # entspicht den uids der sys_language
                'GETvar' => 'LC',
                'valueMap' => array(
                    'de' => '25x54',
                    'gb' => '38x74',
                ),
                'noMatch' => 'bypass',
            ),
            array(
                # muss nach LC-Segment-Umstellung unbedingt enthalten bleiben für die Verarbeitung nach altem Schema
                'GETvar' => 'L',
                'noMatch' => 'bypass',
            ),
            array(
                # muss nach LC-Segment-Umstellung unbedingt enthalten bleiben für die Verarbeitung nach altem Schema
                'GETvar' => 'C',
                'noMatch' => 'bypass',
            ),
        ),
    ),
);`

**Comment by dmitryd** [comment] 2016-07-19 15:17
Duplicate of #186

**Closed by dmitryd** 2016-07-19 15:17 UTC
Labels: duplicate
