### ISSUE TITLE
Warning "config.absRefPrefix is not set" even when page is a shortcut

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#570] opened 2017-11-20 08:33 UTC
Realurl warns "'config.absRefPrefix is not set! Please, check your TypoScript configuration!'" even if the link is encoded by a shortcut page.
https://github.com/dmitryd/typo3-realurl/blob/71d2a169cd744256999ff06e229fa5339e5767c6/Classes/Encoder/UrlEncoder.php#L1340

In this case absRefPrefix is not yet set so the warning is always triggered.

TYPO3 checks if a page is a shortcut here: https://github.com/TYPO3/TYPO3.CMS/blob/a7d63adc3b4d568dee86fe9267b1b069c089269f/typo3/sysext/frontend/Classes/Http/RequestHandler.php#L194

TYPO3 sets absRefPrefix later if the page is not a shortcut: https://github.com/TYPO3/TYPO3.CMS/blob/a7d63adc3b4d568dee86fe9267b1b069c089269f/typo3/sysext/frontend/Classes/Http/RequestHandler.php#L210

I can't find a way to let Realurl to know that the encode link request comes from a shortcut page. Maybe is the core that should set absRefPrefix to `NULL` as default instead of `''` until its value is really set later.

**Comment by adrienjacob** [comment] 2017-11-20 09:26
Hi... I believe this is a duplicate of https://github.com/dmitryd/typo3-realurl/issues/548
See also suggested PR https://github.com/dmitryd/typo3-realurl/pull/563 and pending core ticket https://forge.typo3.org/issues/82939 (to post your `NULL` suggestion maybe)

**Comment by dmitryd** [comment] 2017-12-08 07:35
Closed as duplicate.

**Closed by dmitryd** 2017-12-08 07:35 UTC
