### ISSUE TITLE
Backend Module Error

### ISSUE THREAD

**Issue by kakuschke** [dmitryd/typo3-realurl#64] opened 2016-03-08 17:36 UTC
The Backend Modul show an Error.

**Uncaught TYPO3 Exception**
#1298012500: Required argument "uid" is not set for DmitryDulepov\Realurl\Controller\AliasesController->edit. (More information)

TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file
.../typo3cms/typo3_src-7.6.4/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 430.

Doesnt matter what page.

**Comment by kakuschke** [comment] 2016-03-08 17:39
The page_root is flagged.

**Comment by dmitryd** [comment] 2016-03-09 12:06
Are you sure you [updated correctly](https://github.com/dmitryd/typo3-realurl/wiki/Upgrading-from-RealURL-1.x-to-RealURL-2.x) from version 1?

**Comment by kakuschke** [comment] 2016-03-09 12:20
I removed Version 1 complely and install version 2 from scratch.

**Comment by dmitryd** [comment] 2016-03-09 12:22
No, that will not work because tables will remain in the database. You have to perform correct upgrade steps or realurl will not function properly. Alternatively you can manually remove tables, whose names start from `tx_realurl_` and than install realurl 2.

Missing uid tells that there is no uid field in the database. It means that upgrade was not perforend correctly.

**Comment by kakuschke** [comment] 2016-03-09 12:26
The tables were removed as well. After that I install realurl 2 from scratch. No problems with tables.

**Comment by kakuschke** [comment] 2016-03-09 12:27
Have this something to do with the sys_registry? Maybe

**Comment by dmitryd** [comment] 2016-03-09 12:28
Nothing to do with sys_registry.

**Comment by kakuschke** [comment] 2016-03-09 12:28
ok ;-)

**Comment by peperonilenchen** [comment] 2016-03-18 09:49
Hi, i've got the same error ... Have you got a solution?

**Comment by dmitryd** [comment] 2016-03-18 09:50
https://github.com/dmitryd/typo3-realurl/issues/64#issuecomment-194266057

**Comment by peperonilenchen** [comment] 2016-03-18 09:55
I have deleted all tables with tx_realurl and and the extension. Then i have installed the extension new and i still get this error in backend

**Comment by dmitryd** [comment] 2016-03-18 09:58
Than I can only recommend clearing caches in the Install tool (not at the top of the Backend but in the Install tool!). I have no other ideas because I could never reproduce the problem.

**Comment by dmitryd** [comment] 2016-03-18 10:01
wait, I think I know what the problem is :)

**Comment by dmitryd** [comment] 2016-03-18 10:14
The problem happens this way:

1. Go to Aliases module
1. Select an alias type
1. Click 'Edit' icon for the alias
1. Go to some other page in the page tree

This will be fixed in version 2.0.10

**Closed** 2016-03-18 10:17 UTC
Labels: bug

**Comment by peperonilenchen** [comment] 2016-03-18 10:29
Thank you :-)

**Comment by kakuschke** [comment] 2016-03-18 13:25
Great, Thanx

**Comment by peperonilenchen** [comment] 2016-03-18 14:50
OK , something strange.
I can't genarete the Aliases now - and my URL have got a chash on Detailsite now - like "/single-view/?tx_ttnews[tt_news]=131&cHash=78ceeca0a61571aa79cef7aedacd16d4
![bildschirmfoto 2016-03-18 um 15 49 29](https://cloud.githubusercontent.com/assets/597038/13881392/1013312e-ed21-11e5-8c78-0f163f3ef312.png)
"

**Comment by dmitryd** [comment] 2016-03-18 14:51
Support is provided in mailing lists. Before you post here, you **must** make sure it is a bug.
