### ISSUE TITLE
Automatic Configuration not triggered if hooks are registered in extension loaded before realURL

### ISSUE THREAD

**Issue by fgerards** [dmitryd/typo3-realurl#553] opened 2017-10-27 11:23 UTC
Hi,

if an extension register e.g. a hook in $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['decodeSpURL_preProc'] and this extension is loaded before RealURL, the check in typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php:294 goes wrong and the automatic configuration isnt rebuilt, when the file is deleted to trigger it.

Possible Fix: check if the first key of the array is a hook, e.g. with ( !isset($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']) || in_array( key($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']),['decodeSpURL_preProc','encodeSpURL_preProc',.....])

**Comment by tmotyl** [comment] 2017-10-27 13:52
did you try to add realurl to "suggested" extension in your extension's ext_emconf.php ?
This influences the order in which configuration of extensions is loaded.

**Comment by fgerards** [comment] 2017-10-27 15:25
Tried it in depends AND suggests.
But to understand it better: 
Here we have to conflicting "interests":

a) RealURL needs to be aware of ALL registered hooks. Hooks live inside the $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] array. This is assured by using the depends/suggests feature.

b) the condition inside the function to regenerate the autoconfig needs an EMPTY $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] - array. This is NEVER true if you register hooks in own extensions (e.g. the ['decodeSpURL_preProc'] hooks we use).

Thus the if-condition is wrong, a clear bug. Either move the hook-register-keys out of the  $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] Array or extend the if-condition, e.g. in the way I did. Works for us.

**Comment by helfalt** [comment] 2017-11-08 10:14
Is the first part in the following condition inside method performAutomaticConfiguration() really needed? From my point of view a check for enabled autoconfiguration should be sufficient, i. e.:

protected function performAutomaticConfiguration() {
  if ($this->extConfiguration['enableAutoConf']) {   ...   }
}

**Comment by fgerards** [comment] 2017-11-12 15:25
Hmm u then would regenerate the file on every request...

**Comment by helfalt** [comment] 2017-11-13 08:10
Only, if it does not exist... (see $autoconfigurator->configure();) 

But it is not optimal anyway...

I suggest to proceed as follows:
1. check if realurl is loaded and autoconfiguration ist set in extension settings
2. if 1) is true check if autoconf file exists
3 if autoconf file does not exist handle locker and invoke method runConfigurator()

**Comment by dmitryd** [comment] 2017-12-08 07:32
@fgerards The possible fix is not really a fix because there are many options that can be set in the realurl config. If you depend on realurl, you have to add it to dependencies in your extension. This is what dependencies are for: to allow extensions work in the right order.

**Comment by helfalt** [comment] 2017-12-12 08:50
@dmitryd Sure, but this behaviour arises even though a constraint ("depends" or "suggests") is added in ext_emconf.php in my extension. So, I can confirm what @fgerards has found. In my mind it is a real bug and should be fixed.

**Comment by fgerards** [comment] 2018-01-02 11:02
@dmitryd : exactly, but realurl is buggy, if all extensions are loaded in the right order:
As I stated, if I add the depends/suggests dependency, the decode/encode - hook isnt processed at all, because at processing time of realurl, the hook is not registered. Only way to circumvent this is to register the hook BEFORE realurl processing starts. But that triggers the mentioned error when deciding, if automatic configuration array should be generated.

**Comment by christoph-bessei** [comment] 2018-01-02 14:14
Same problem here. 
It doesn't matter if realurl is added as dependency/suggested extension, since ext_localconf.php (where we register the hook to decodeSpURL_preProc) is executed way before the automatic configuration is triggered (from linkData-PostProc in TemplateService). The condition in ```performAutomaticConfiguration``` is always false.

So at the moment either hooks to decodeSpURL_preProc OR automatic configuration is possible.

**Comment by dmitryd** [comment] 2018-01-08 15:26
@fgerards 
>  if I add the depends/suggests dependency, the decode/encode - hook isnt processed at all, because at processing time of realurl, the hook is not registered.

This is not right. Decode hook is executed after `ext_localconf.php` is processed. Encode hook is executed even later. Check how you define hooks...

**Comment by stucki** [comment] 2018-02-21 15:55
Here is a patch which fixes the problem:
```
diff --git a/ext_localconf.php b/ext_localconf.php
index be2c9e6..a922f7b 100644
--- a/ext_localconf.php
+++ b/ext_localconf.php
@@ -24,6 +24,9 @@ if (!function_exists('includeRealurlConfiguration')) {
                        );
                }
 
+               // Preserve the existing array as it may hold hook configuration which is not part of the configFile
+               $initialRealurlConfiguration = $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'];
+
                $realurlConfigurationFile = trim($configuration['configFile']);
                if ($realurlConfigurationFile && @file_exists(PATH_site . $realurlConfigurationFile)) {
                        \TYPO3\CMS\Core\Utility\GeneralUtility::requireOnce(PATH_site . $realurlConfigurationFile);
@@ -32,6 +35,14 @@ if (!function_exists('includeRealurlConfiguration')) {
                        /** @noinspection PhpIncludeInspection */
                        @include_once(PATH_site . TX_REALURL_AUTOCONF_FILE);
                }
+
+               if (is_array($initialRealurlConfiguration)) {
+                       $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] = array_merge(
+                               $initialRealurlConfiguration,
+                               $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']
+                       );
+                       unset($initialRealurlConfiguration);
+               }
        }
 }

```

**Closed** 2018-02-26 13:53 UTC
