### ISSUE TITLE
Pages from different rootpages, having the same "Speaking url path segment", both get encoded with the same rootpage_id

### ISSUE THREAD

**Issue by eliademoga** [dmitryd/typo3-realurl#419] opened 2017-02-27 09:11 UTC
When having more than one domain on a TYPO3 installation and at least two of them have pages configured to "Override the whole page path" and their "Speaking url path segment" is the same across domains then the url path segment is encoded for both pages using the current rootpage_id which then leads to a 404 response when the actual page is accessed.

**Comment by dmitryd** [comment] 2017-03-03 12:56
Here is what I did:

- Create a page named "Override test" with a spwaking path segment set to `/override419`
- Copy this page to a second domain and unhide it
- Visit the root page of the first domain and go to the "Override test" page. It opens with the expected content and url
- Visit the root page of the second domain and go to the "Override test" page. It opens with the expected content and url

Thus I can conclude that the issue is not reproducible for me. If you have a different page structure, you need to describe it here. Otherwise it is not fixable.

**Comment by eliademoga** [comment] 2017-03-07 10:00
Hello,
thanks for the reply.

The issue was present on one of our clients site on TYPO3 7.6.15 and realurl 2.1.5. I've also tested this on realurl 2.1.7 (latest at that time) and the issue was still there.
I'll check if this is reproducible on a fresh install and the same structure as on the clients site and get back if it's still an issue.

Best regards,
Cristian

**Comment by dmitryd** [comment] 2017-04-08 11:10
No feedback provided, closing the issue.

**Closed by dmitryd** 2017-04-08 11:10 UTC
Labels: needs feedback, not reproducible
