### ISSUE TITLE
Exclude from speaking URL throws error for multilanguage

### ISSUE THREAD

**Issue by dermueller** [dmitryd/typo3-realurl#87] opened 2016-03-17 18:57 UTC
Hello Dmitry,

I have a setup with 2 languages ("de" (L=0) and "en" (L=1)) and a page structure like this:

- Homepage
- - Subpage1
- - Footer-Navigation (SYSFOLDER)
- - - FooterpageDE1 (translated to FooterpageEN1 for L=1)

If I do NOT select "Exclude from speaking URL" for the Sysfolder "Footer-Navigation", everything is fine. I get this link for DE:
domain.de/footer-navigation/footerpagede1/
And this link for EN:
domain.de/en/footer-navigation/footerpageen1/

But when I DO select "Exclude from speaking URL", I get for DE:
domain.de/footerpagede1/ (which is correct)
but for EN (while I should get domain.de/en/footerpageen1/):

Page Not Found
Reason: Segment "footerpageen1" was not a keyword for a postVarSet as expected on page with id=2.

Everything else is working fine. Can this be a bug in RealURL?

Best regards

Thomas

P.S.: I should add that I use TYPO3 6.2.19 with RealURL 2.0.9 - a clean new installation, so no upgrade from RealURL Version 1 made.

**Comment by dmitryd** [comment] 2016-03-18 06:27
Duplicate of #80. Already fixed. Please, wait for the 2.0.10 release today.

**Closed by dmitryd** 2016-03-18 06:27 UTC
