### ISSUE TITLE
Shortcut pages redirected to decoded url

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#577] opened 2017-12-10 13:56 UTC
After commit https://github.com/dmitryd/typo3-realurl/commit/54c5233041f7ba272ac61a6c2c2f08950294c0c8 (fixing https://github.com/dmitryd/typo3-realurl/issues/548 & https://github.com/dmitryd/typo3-realurl/issues/570) when I browse a shortcut page, it redirects to the target but using the decoded url.

By instance, we have a page with title "shortcut" that has as target a page with title "target" and uid=123.
When I browse: `http://foo.bar/shortcut/` it should redirects to `http://foo.bar/target/` but instead it redirects to `http://foo.bar/index.php?id=123`

After a quick check, new method `getAbsRefPrefix()` prepends a slash to index.php while, before the commit this didn't happen.

**Comment by dmitryd** [comment] 2017-12-14 08:37
Can't reproduce this.

**Comment by JNellissen-BM** [comment] 2017-12-14 09:09
We have a similiar problems with real url and TYPO3 shortcut pages.
In our case it seems, there is a problem between realurl and the server config.
On our dev Systems everything is fine and the shortcut url will be  generated like expected, but on the client server every shortcut redirects to the standard TYPO3 url (index.php?id=XXX)
I can't figure out where are the differents (I have no direct access to the client server) and everything looks nearly identical, but I guess, some information from the request should be wrong, so the domain could not be determined correctly... or something else ;-)
I am sorry, I can't give you more information beside that I can confirm this problem,
or like we say in german "Irgendwo ist da der Wurm drin" ;-)

Kind regards
Jeffrey

**Comment by fgerards** [comment] 2017-12-14 13:21
its reproducable here to: after update to 2.3.1, shortcut target-url is not realurl-encoded anymore.
Instead, it redirects to index.php?id=<id>. This is a major bug and would cause google rankings to drop.
plz fix, thank you !

**Comment by mbrodala** [comment] 2017-12-14 13:57
I can also confirm the issue:

- 2.3.0: `/shortcut/` redirects to `/target/`
- 2.3.1: `/shortcut/` redirects to `/index.php?id=N`

Downgrading to 2.3.0 restores the correct behavior.

**Comment by christian-hellmuth** [comment] 2017-12-15 08:40
I can also confirm the described misbehavior. Not going into further detail as it's already been described correctly before.

**Comment by automatrix** [comment] 2017-12-15 16:57
I can also confirm this - I also had to downgrade to v. 2.3.0 to have it work again.

**Comment by rafu1987** [comment] 2017-12-20 10:35
I can also confirm this and a downgrade to 2.3.0 helped.

**Comment by corth** [comment] 2017-12-20 13:52
Can confirm that, downgrade to 2.3.0 also hepled for me.

**Comment by dmitryd** [comment] 2017-12-22 09:03
Can somebody reproduce this with my [Docker-based test site project](https://github.com/dmitryd/typo3-test-site)? Before I can fix it, I need to find why this happens.

**Comment by thasmo** [comment] 2017-12-22 13:32
Same issue here. Gonna try to find some time to test it using the test-site later.

**Comment by chris246** [comment] 2017-12-22 19:22
Same issue here.
Redirects using page shortcuts change the url to `index.php?id=N`

Resetting the realurl config for this page didn't help. Downgrading to v 2.3.0 fixed the issue

**Comment by stiffelstuff** [comment] 2018-01-04 10:42
Same here ... 2.3.0 for now

**Comment by dmitryd** [comment] 2018-01-05 08:53
I still need a way to reproduce this. Without reproducing I cannot fix it. Could somebody try with the test site project?

**Comment by chrisprog20** [comment] 2018-01-05 14:45
This happens if 
`config.absRefPrefix = / `
is set.

I tested this in TYPO 7.6.23 and this happened after upgrading to realurl 2.3.1.

I think it has to do with commit [54c5233](https://github.com/dmitryd/typo3-realurl/commit/54c5233041f7ba272ac61a6c2c2f08950294c0c8) (fixing #548 & #570).

If I set

`config.absRefPrefix >`

the error does not happen but then I get again an entry in typo3temp/logs 
giving the message like in #548 or #570.

**Comment by mbrodala** [comment] 2018-01-05 14:50
@chrisprog20 Can you try with `config.absRefPrefix = auto` while you're at it?

**Comment by chrisprog20** [comment] 2018-01-05 14:55
@mbrodala: with `config.absRefPrefix = auto`  it behaves like with `config.absRefPrefix = /`.

**Comment by fgerards** [comment] 2018-01-06 14:08
config.absRefPrefix=/ is used in a lot of our projects to avoid any relative paths and ensure the current domain is correctly set in links.

**Comment by AndreasA** [comment] 2018-01-08 08:39
Same issue here. The problem is that isTypo3Url does not match with the produced redirect URL anymore because TYPO3 does not have $GLOBALS['TSFE']->absRefPrefix set when generating the shortcut URL.
However, realurl in order to avoid the false log entries now manually parses the absRefPrefix calling getAbsRefPrefix which is wrong for the isTypo3Url check.

**Comment by dmitryd** [comment] 2018-01-08 10:01
Hm.... Any ideas how to fix this and avoid reintroducing old issues? Shouldn't this actually be fixed in the core (set absRefPrefix before redirects)?

**Comment by AndreasA** [comment] 2018-01-08 11:39
I already created a corresponding core ticket in the old ticket and yes I agree it should be fixed there.
https://forge.typo3.org/issues/82939
Just didn't find the time to fix it there yet. Maybe someone else can. It should only be necessary to move the absRefPrefix set before doing the shortcut / mountpoint redirects.

I think what would work is to only use $GLOBALS['TSFE']->absRefPrefix in isTypo3Url - as it would be set for all later URLs and not set for the shortcut redirect - but use getAbsRefPrefi everywhere else.
However, it is a workaround.

**Comment by DrillSergeant** [comment] 2018-01-18 16:37
I confirm that downgrading to 2.3.0 solved the problem. Intermediate solutions for me untill TYPO3 8.7.8 with realurl 2.3.1 is stable again in this regard.

**Comment by jean-alex** [comment] 2018-01-24 02:52
I confirm that the problem comes with v2.3.1 and downgrading to 2.3.0 is a workaround!

**Comment by hartundweich** [comment] 2018-01-31 14:05
Same here - downgrading to 2.3.0 solved the issue.

**Comment by linkpool** [comment] 2018-01-31 14:11
The problem is for us, that we use in all our setups something like this;

TYPO3-root
- web01root
-- home
- web02root
-- home
- web03root
-- home

Something like www.web01root.com should redirect to www.web01root.com/de/home

With the bug in 2.3.1 the user will be redirected to www.web01root.com/index.php?id=n

**Comment by runout-at** [comment] 2018-02-06 17:00
Same here. Confirm this.

**Comment by foobar13373** [comment] 2018-02-07 11:36
Confirmed. 2.3.1 does the redirect, 2.3.0 does not. Tested on 7 and 8 LTS.

**Comment by mbrodala** [comment] 2018-02-07 11:50
@foobar13373 
> Confirmed. 2.3.1 does the redirect, 2.3.0 does not. Tested on 7 and 8 LTS.

Both do the redirect, only 2.3.1 redirects with a raw URL.

**Comment by foobar13373** [comment] 2018-02-07 15:01
@mbrodala Sorry for being imprecise, I updated my comment.

**Comment by AndreasA** [comment] 2018-02-08 13:12
Created a PR that should fix this behaviour.

**Comment by mbrodala** [comment] 2018-02-08 13:12
You mean #598 I guess.

**Comment by AndreasA** [comment] 2018-02-08 13:13
Yes.

**Comment by linkpool** [comment] 2018-02-08 17:00
[BUGFIX] shortcuts need to redirect to encoded URLs 

Works fine for us!

**Comment by chrisprog20** [comment] 2018-02-08 18:58
Thank you AndreasA!
The thing is though that your fix will reintroduce issue #548.
See also for this: https://github.com/dmitryd/typo3-realurl/commit/54c52330.

**Comment by AndreasA** [comment] 2018-02-08 19:06
Not it won't as this change is only used for isTypo3Url.
Not during the other part where e.g. the check for logging is done.

**Comment by AndreasA** [comment] 2018-02-08 19:15
Added a comment there to make this difference clear.

**Comment by vmans** [comment] 2018-02-10 12:54
Works for me. Thanks for sharing this solution Andreas.

**Comment by foobar13373** [comment] 2018-02-23 06:56
@dmitryd (When) Will you merge this patch and do a new release?

**Comment by emileblume** [comment] 2018-02-23 07:59
I've tested this in two seperate 8.7.10 installations with 2.3.1 and config.absRefPrefix = auto or config.absRefPrefix = / but the redirects work as expected, with the correct path.
We haven't had any complaints from our customers either

**Comment by emileblume** [comment] 2018-02-23 08:23
@mbrodala Maybe it concerns the way realURL is configured?

**Comment by AndreasA** [comment] 2018-02-23 10:36
Are you sure you have redirects? Check network tab in Developer Tools with Preserve log to be sure.
For instance, in a menu the shortcut might not redirect but immediately generate the correct URL.
And in RTE content links that have specified a target page and you have set 
**config.typolinkCheckRootline = 1**
then you will get the correct URL there too. However, e.g. for shortcut pages of type first sub-page that is not the case.

The easiest way to test this issue (tested with realurl 2.3.1 and TYPO3 8.7.10):
1. Create a shortcut page with option first sub-page
1. Add a sub page to that shortcut page
1. Add a Text & Media Element with a link in the bodytext that references the shortcut page (not the target page)
1. Viewing the result will output the following link /shortcut-page/ and not /shortcut-page/first-sub-page/
1. Clicking on the link will result in redirect to some index.php?id=....

Optionally you can also use a header link as long as the linked page is the same.

It shouldn't be a realurl config as that doesn't have an impact on the check I changed in the PR.

And I have set the following Typoscript:
```
config.absRefPrefix = /
config.typolinkEnableLinksAcrossDomains = 1
config.typolinkCheckRootline = 1
config.tx_realurl_enable = 1
```

**Comment by emileblume** [comment] 2018-02-23 10:46
@AndreasA After following your steps I can reproduce the problem. If the shortcut mode is set to 'Selected page' all goes well.

**Comment by hartundweich** [comment] 2018-02-23 11:06
Here not working when using configuration from AndreasA

> config.absRefPrefix = /
> config.typolinkEnableLinksAcrossDomains = 1
> config.typolinkCheckRootline = 1
> config.tx_realurl_enable = 1

When setting shortcut mode to "Selected Page" resulting url is still index.php?id=....

**Comment by DrillSergeant** [comment] 2018-02-23 11:57
I wonder if the label "not reproducible" still makes sense

**Comment by hartundweich** [comment] 2018-02-23 11:59
OK now I understand - I'm redirecting to a selected page (just one level below the source page) and this is not working - I'll wait for the fix and in the meantime I'll continue using 2.3.0 on all my projects until this bug is fixed.

**Comment by dmitryd** [comment] 2018-02-26 12:03
@mbrodala 

> The issue has been confirmed by many and acknowledged by @dmitryd already

Well, it wasn't. As I said, I cannot reproduce it in my test project. I already gave a link to it numerous times and asked others to test.

To all: do you see any side effects from the fix by @AndreasA?

**Comment by mbrodala** [comment] 2018-02-26 14:56
@dmitryd Well, I tried to bring up your test environment but [failed](https://github.com/dmitryd/typo3-test-site/issues/1).

**Comment by AndreasA** [comment] 2018-02-26 16:39
@dmitryd : Have you tried the steps I mentioned at https://github.com/dmitryd/typo3-realurl/issues/577#issuecomment-367973122 ?
Currently I don't have docker setup to test with your docker environment.

**Comment by adymorz** [comment] 2018-02-28 11:07
The problems with wrong encoding on shortcuts just happend on a website I am working on.

I tried the fix provied by @AndreasA: The wrong encoded URLs on shortcuts is gone and I could not find any side effects.

Thank you for your great work, @dmitryd and @AndreasA

**Comment by typecat** [comment] 2018-02-28 11:17
Can confirm this in 2 projects (TYPO3 7.6 and TYPO3 8.7 )as @hartundweich described.
Scenario:          "root page" [1] links to "homepage" [4]
RealURL 2.3.0: project.test > project.test/de/startseite
RealURL 2.3.1: project.test > project.test/index.php?id=4&L=0

Also tried the fix provied by @AndreasA without success. Had to downgrade to RealURL 2.3.0 in both projects.

**Comment by Ben305** [comment] 2018-03-01 09:03
Same problem here, downgrading to RealURL 2.3.0 is working as expected.

Scenario: "Root page" [2] links to first subpage [332]

**Comment by foobar13373** [comment] 2018-03-06 07:15
@dmitryd 
I'd say the fix from @AndreasA helps most people and does not make it worse for the rest where it does not work, so it should be integrated and released as soon as possible.

**Comment by dmitryd** [comment] 2018-03-07 10:10
Merged. Thanks to everybidy and especially @AndreasA

**Closed** 2018-03-07 10:10 UTC
Labels: not reproducible
