### ISSUE TITLE
Speaking URL settings in page properties not working

### ISSUE THREAD

**Issue by wi-holzem** [dmitryd/typo3-realurl#443] opened 2017-03-20 12:17 UTC
Hello,

i have the problem, that the Speaking URL settings ("Speaking URL path segment " and "Exclude from speaking URL ") not working. The URL it still uses "Page Titel" and "Excluded" Pages are also part of the URL.
So far i have tried with the automatic configuration an different manual configurations. I cleaned the realURL Path by turncate the tx_realurl-Tables directly in the DB several times but everything without success.

I use Typo3 7.6.16 an RealURL 2.1.9
I attached my realurl_conf.php:
[realurl_conf.php.txt](https://github.com/dmitryd/typo3-realurl/files/854891/realurl_conf.php.txt)

Thanks for your help

**Comment by dmitryd** [comment] 2017-03-28 07:51
I cannot reproduce the issue.

The old url will still work for some time but it redirects to a new url for SEO reasons.

**Comment by adrienjacob** [comment] 2017-03-28 07:57
@wi-holzem : maybe just try clearing the front-end cache (sorry if you did and I'm being too obvious) ? Otherwise an extract of the tx_realurl tables for a given page, before and after a change in settings, would help to understand.

**Comment by wi-holzem** [comment] 2017-03-28 08:11
i cleaned the cache several times, also truncate the tx_realurl Tables directly in the DB. Nothing works.
The (news) Records in the tx_realurl Tables are the same after clearing them. The Records dont change when i set "Execlude from Speaking URL" to true

**Comment by dmitryd** [comment] 2017-03-28 09:34
Are you trying to exclude the very last page (like a news detail page)? This will not work. Only pages in the middle can be excluded.

**Comment by wi-holzem** [comment] 2017-03-28 10:03
No, some examples i want to exclude:
# Navigation-Menu in Footer:
Footer (Folder) -> Information(Folder) -> Imprint (Page)
-> i try to excluded "Footer" and "Information" 
--> i solved this with "Override whole path"
# Page:
Services (Page) -> Webdevelopment (Page) -> Typo3 (Page)
-> i try to excluded "Services"
my URL: mywebsite.de/service/webdevelopment/typo3
i want URL: mywebsite.de/webdevelopment/typo3
# News:
News (Page / Overview) -> Detail (Page / Detail) --> News01 (News Article)
-> i try to excluded "Detail"
isn't it possible to hide "Detail" from News?
my URL: mywebsite.de/news/detail/news01
i want URL: mywebsite.de/news/news01

**Comment by dmitryd** [comment] 2017-03-28 10:25
> isn't it possible to hide "Detail" from News?

No, because it is the last segment. Reason: `mywebsite.de/news/` will refer to both news list and news detail page. It is impossible to resolve when one url refers to two pages. So the last segment never can be excluded.

**Comment by wi-holzem** [comment] 2017-03-29 06:51
okay, but 

Services (Page) -> Webdevelopment (Page) -> Typo3 (Page)
-> i try to excluded "Services"
my URL: mywebsite.de/service/webdevelopment/typo3
i want URL: mywebsite.de/webdevelopment/typo3

should working, am i right?

**Comment by dmitryd** [comment] 2017-03-29 07:20
Yes, they are. We use this feature all the time for our sites.

**Comment by wi-holzem** [comment] 2017-04-05 09:35
Do you know why the others not working?
Do i have a error in the realurl_conf.php?
Also the Speaking URL not working it uses always "Page Titel"

**Comment by dmitryd** [comment] 2017-05-07 12:14
I tested once again and I cannot reproduce the issue. You need one of your php devs to check the installation. It is not possible to help remotely with this.

I am closing the issue because it is not reproducible.

**Closed by dmitryd** 2017-05-07 12:14 UTC

**Comment by geri777** [comment] 2018-04-02 10:20
I have exactly the same problem. I have a structure like this:
/aaa/page1
/aaa/page2
/aaa/page3

I set **Speaking URL path segment** to "page1" for "/aaa/page1" etc.
I set  enable **Override the whole page path** for each of them
I delete all tx_realurl_* tables using SQL
I clear caches (**flush all caches**)

For some reason /aaa/page1 works, but **all links to page2 and page 3 still include the folder /aaa/**.
However both links would work: 
/aaa/page2 and /page2 works if I enter them manually in the browser.
