### ISSUE TITLE
Page can be reached under two URL, although Speaking Path URL Segment and Override the whole page path is set

### ISSUE THREAD

**Issue by DietmarBlue** [dmitryd/typo3-realurl#149] opened 2016-04-29 11:34 UTC
**Page Title** is 'gourmet', 
**Speaking Path URL Segment** is 'gourmet-hotel-oesterreich'
**Override the whole page path** is checked

Subpage can be reached under 2 URL, which causes duplicate content
de/gourmet/weinkultur/ and 
de/gourmet-hotel-oesterreich/weinkultur/

I would expect, that the subpage can only be reached under de/gourmet-hotel-oesterreich/weinkultur/ because of the checked **Override the whole page path** checkbox

**Comment by dmitryd** [comment] 2016-04-29 11:38
You can expect that but this is not how realurl works. Set up redirects if you do not want one of these two urls to work.

Not a bug.

**Comment by DietmarBlue** [comment] 2016-04-29 11:41
Hi Dimitri.

Thank you for your superfast answer!


Viele Grüße,
Dietmar


Dietmar Lamprecht
Web Developer
--------------------------------------------------------------------------------
IT-News, Aktionen & Specials ><http://www.bluechip.at/de/news/>
BlueChip Newsletter abonnieren ><http://www.bluechip.at/de/news/newsletter/>
BlueChip Fernwartungs-Unterstützung ><http://fw.bluechip.at/>
---------------------------------------------------------------------------------
BlueChip Software GmbH
Hochtennstrasse 30
A-5700 Zell am See
Tel.: +43 6542 57584-0
Fax: +43 6542 57584-4
Web: www.bluechip.at<http://www.bluechip.at/>
Firmenbuchnummer: 32658b
Firmenbuchgericht: LG Salzburg

Von: Dmitry Dulepov [mailto:notifications@github.com]
Gesendet: Freitag, 29. April 2016 13:38
An: dmitryd/typo3-realurl
Cc: Dietmar Lamprecht (BlueChip Software GmbH); Author
Betreff: Re: [dmitryd/typo3-realurl] Page can be reached under two URL, although Speaking Path URL Segment and Override the whole page path is set (#149)


You can expect that but this is not how realurl works. Set up redirects if you do not want one of these two urls to work.

Not a bug.

**Comment by fschwaiger** [comment] 2016-05-05 15:30
Could it be that, after editing the page URL segment, the old URL is still in the decode cache? So the newly generated URLs will now be all de/gourmet-hotel-oesterreich/weinkultur/, but both URLs will be decoded to the same page id? You can verify this in the info module, I just found such a case on my own page:

<img width="682" alt="realurl_decode_cache" src="https://cloud.githubusercontent.com/assets/1839759/15047797/dcf4179a-12e6-11e6-85f7-50a0b6d8fab2.png">

**Comment by DietmarBlue** [comment] 2016-05-06 05:56
Thank you for the hint, but we are always disabling this functionality in realurl_conf, because it makes often troubles.
`	'init' => array(`
`		'enableUrlDecodeCache' => 0,`
`		'enableUrlEncodeCache' => 0,`

**Comment by dmitryd** [comment] 2016-05-06 06:53
You will get performance issues if you disable caches and may have other side effects.

RealURL usually redirects to a newer path, so it is not a problem for SEO. Availability for previous URLs is actually made to make sure that users, who come from search engines, don't get 404s.

**Comment by dmitryd** [comment] 2016-05-06 14:37
By the way, this bug report refers to realurl 1.x, which is not supported any more. Closing the issue.

**Closed by dmitryd** 2016-05-06 14:37 UTC
