### ISSUE TITLE
Malformed cache of a mounted page

### ISSUE THREAD

**Issue by andrewhowdencom** [dmitryd/typo3-realurl#644] opened 2018-08-31 14:56 UTC
Holaa,

We're experiencing a problem in which the incorrect page URL is being matched against a page. I believe I've traced the problem down to the `UrlDecoder.php` file; specifically, when it's decoding the URL initially it has no notion of the mount point. Later, somehow it appears that this works as expected.

The relevant parts of the tree look like so:

```
+ Central
-- + Foo <-- This is the page that is mounted against.
---- + Bar
----- + Baz

+ Local
-- + Berlin
---- + Meta <-- This page  has the property "exclude from speaking URL"
------ + Foo <-- This is the page mounted to the aforementioend "Foo"
```

To reproduce the issue it works as so:

1. Visit the `/local/berlin/foo` page

Everything works correctly

2. Visit the `/local/berlin/foo` page again

The page from `/central/foo` is displayed.

During the path render, the page is incorrectly saved without a mount point reference to `tx_realurl_pathdata`. Then, when the page is loaded, the page `tx_realurl_pathdata` without this mount point is shown.

During debugging, this particular set of code does not seem to be entered:

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L352-L357

and the path is cached here:

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L511

The path is correctly generated by the following code:

```
https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L511
```

But I haven't looked heaps into how that generates it correctly. 

I'm unsure how best to resolve this one. If you have any ideas, they'd be much appreciated. Disabling the `putPathToCache` line (simply commenting it out) resolves this, but I can't really deploy that.

**Comment by dmitryd** [comment] 2018-09-23 12:52
> I believe I've traced the problem down to the UrlDecoder.php file; specifically, when it's decoding the URL initially it has no notion of the mount point

Decoding without having entries in the urldata or pathdata is limited and incomplete (for example, unique aliases cannot be resolved this way). I will have a look.

**Comment by dmitryd** [comment] 2018-09-23 12:55
However I am not getting what is wrong. Here is what you describe:

To reproduce the issue it works as so:

> 1. Visit the /local/berlin/foo page
> Everything works correctly
>
> 2. Visit the /local/berlin/foo page again
> The page from /central/foo is displayed.

Not sure what "correctly" in case 1 means but case 2 looks right because according to your description /local/berlin/foo should display /central/foo.

Please, correct me if I misunderstand something.

**Comment by andrewhowdencom** [comment] 2018-09-24 10:13
Hola @dmitryd; 

> Not sure what "correctly" in case 1 means but case 2 looks right because according to your description /local/berlin/foo should display /central/foo.

Sortof. In the scenario where:

`/local/berlin/foo`

is being viewed, the version of the page that is being returned does not link to:

`/local/berlin/bar` 

but rather to

`/berlin/bar`

In other words, the page shows the links to the non-mounted content. Does that make sense?

**Comment by dmitryd** [comment] 2018-09-24 14:17
@andrewhowdencom Which page in the tree is of type "Mount point"?

**Comment by dmitryd** [comment] 2018-09-24 14:19
@andrewhowdencom If I understand correctly, `/local/berlin/foo` should link to `/central/foo`. Is this correct?

**Comment by andrewhowdencom** [comment] 2018-09-24 16:48
Hola @dmitryd; 

In the example above, the page `/local/berlin/foo` is the mount point, pointing to `/local/foo`. 

So, the paths you describe are correct. But, the navigation has notion of what mount point the page renders -- even though the page:

```
/local/berlin/foo
```

is mounted to

```
/central/foo
```

It still has notion that it is a mounted page, and thus the navigation should direct users within the mounted page, rather than to the original page. For example,  given:

```
/local/berlin/foo/bar
```

containing a link to "baz" should link to 

```
/local/berlin/foo/baz
```

and not 

```
/central/foo/baz
```

Does that make sense? cc @cyb3r who might be able to explain this in more detail. I might be able to get a concrete example to you also -- would this help?

**Comment by dmitryd** [comment] 2018-09-26 09:56
Yes, this is correct. I will try to make similar setup in my test host and see if I can reproduce this. It is possible that exclusion + mount points does something wrong.

**Comment by dmitryd** [comment] 2020-04-25 13:07
I still cannot reproduce it. Closing :(

**Closed by dmitryd** 2020-04-25 13:07 UTC
Labels: not reproducible
