### ISSUE TITLE
Sub pages of page type spacer not accessible

### ISSUE THREAD

**Issue by klodeckl** [dmitryd/typo3-realurl#57] opened 2016-03-07 14:06 UTC
Since I upgraded to Realurl 2 the pages which are subpages of pages type spacer for menu are not accessible anymore. After changing the doctype to folder it works again.

**Comment by dmitryd** [comment] 2016-03-07 14:07
Duplicate of #54.

**Closed by dmitryd** 2016-03-07 14:07 UTC
Labels: duplicate
