### ISSUE TITLE
Problem with default domain handling

### ISSUE THREAD

**Issue by geraldaistleitner** [dmitryd/typo3-realurl#526] opened 2017-08-31 13:17 UTC
If a user visits a website with a domain that has no record it should be redirected to the top level root page domain. Current behavior is then following:
`$this->setRootPageIdFromDomainRecord() || $this->setRootPageIdFromRootFlag() || $this->setRootPageIdFromTopLevelPages();`
But if there are more then one _is_siteroot_ pages, setRootPageIdFromTopLevelPages get's never called. Better handling would be to fallback to setRootPageIdFromTopLevelPages if there are more than one _is_siteroot_ pages and not throw an error.

**Comment by dmitryd** [comment] 2017-09-08 14:32
Please, configure realurl correctly. Realurl will not adjust to your errors.

**Comment by dmitryd** [comment] 2017-09-08 14:50
I want to explain more.

> If a user visits a website with a domain that has no record it should be redirected to the top level root page domain

Why should it? By design realurl must have the information about all configured domains. This is a requirement. If such information is not provided, realurl tries to fetch it until it exhausts all options. If it cannot determine the domain, it will not use the first available domain or anything else. It will clearly show that there is an error. Why? Because errors should be fixed, not hidden.

So, please, fix your configuration.

**Closed by dmitryd** 2017-09-08 14:50 UTC
