### ISSUE TITLE
createAliasForValue: Empty $getVarValue needs a return false

### ISSUE THREAD

**Issue by abmerlin** [dmitryd/typo3-realurl#233] opened 2016-08-18 08:12 UTC
Hi again,
I have three lookUpTable statements in one part. When e.g. the second and third param is empty the real url calc a url like “…/first-param/-7252c1e077/-9ef7c1d087.html”. 
I think I have found the solution: In the UrlEncoder->createAliasForValue there is no breakout when the param $getVarValue is empty. I have add now at first in the function the flowing:
```
if (empty($getVarValue)) {
    return false;
   }
```

It would be nice to add this to the repository

Thanks a lot
Andreas

**Comment by dmitryd** [comment] 2016-08-18 08:26
Firsts, this will not work because if there is a second postVarSet, it will not be processed correctly.

Secondly, you should not have vars in the same potVarSet if they can be empty. Move to a separate postVarSet.

Closing because it is not a bug.

**Closed by dmitryd** 2016-08-18 08:26 UTC

**Comment by dmitryd** [comment] 2016-08-18 08:40
No, I cannot help. Please, see [Getting help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help).
