### ISSUE TITLE
get-parameter "type" twice in robots.txt and sitemap.xml url generated by metaseo 

### ISSUE THREAD

**Issue by derBoogie** [dmitryd/typo3-realurl#499] opened 2017-07-05 10:20 UTC
robots.txt and sitemap.xml url generates urls with double get-paramter "type" on my website:
http://www.jh-moehringen.de/robots.txt -> http://www.jh-moehringen.de/index.php?id=3&type=841133&type=841133
http://www.jh-moehringen.de/sitemap.xml ->http://www.jh-moehringen.de/index.php?id=3&type=841132&type=841132

I'm using the TYPO3 extension metaseo

my realurl config:
```
...
'fileName' => array (      
	'index' => array (
		...
		'sitemap.xml' => array (
			'keyValues' => array (
				'type' => 841132,
			),
		),
		'sitemap.txt' => array (
			'keyValues' => array (
				'type' => 841131,
			),
		),
		'robots.txt' => array (
			'keyValues' => array (
				'type' => 841133,
			),
		),
	),
),
...
```

MetaSEO version: 3.0.0
TYPO3 version: 8.7.2
PHP version: 7.1.6
RealUrl version: 2.2.1

The developer og metaseo says, it must be a bug in realurl: https://github.com/webdevops/TYPO3-metaseo/issues/497

Is that right?

**Comment by dmitryd** [comment] 2017-07-06 06:27
I do not get the idea.

http://www.jh-moehringen.de/robots.txt is a URL produced by realurl.
http://www.jh-moehringen.de/index.php?id=3&type=841133&type=841133 is not a URL produced by realurl.

So what is the problem with realurl here?

**Comment by thomaszbz** [comment] 2017-07-06 10:43
The problem is that the user is redirected to the URL with duplicate parameters (whereever it comes from) when requesting the URL which _is_ generated by realurl.

```
wget http://www.jh-moehringen.de/robots.txt
--2017-07-04 16:55:37--  http://www.jh-moehringen.de/robots.txt
Auflösen des Hostnamen »www.jh-moehringen.de (www.jh-moehringen.de)«... 46.30.61.6, 2a03:2a00:1200:0:1::3498
Verbindungsaufbau zu www.jh-moehringen.de (www.jh-moehringen.de)|46.30.61.6|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 307 Temporary Redirect
Platz: http://www.jh-moehringen.de/index.php?id=3&type=841133&type=841133 [folge]
--2017-07-04 16:55:38--  http://www.jh-moehringen.de/index.php?id=3&type=841133&type=841133
Wiederverwendung der bestehenden Verbindung zu www.jh-moehringen.de:80.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 160 [text/plain]
```

A nice solution would be to not http forward at all.

If it is wanted behaviour or somehow necessary to 307-forward then the url params should not duplicate.

So it comes down to the question where the URL of the 307-forward is generated. Do you agree that this could only by realurl or the TYPO3 core?

**Comment by dmitryd** [comment] 2017-07-06 14:14
ReaURL does not redirect to original URLs. It may redirect to new URLs but those URLs will always be produced by RealURL. So they cannot have any `type` parameters in them.

In addition when RealURL redirects, its HTTP header is like `HTTP/1.1 301 RealURL Redirect` and there is an additional HTTP header named `X-TYPO3-RealURL-Info`, which tells you why the redirect happen. Now if you check how your redirect happens:

```
MBP3:~ $ curl -I http://www.jh-moehringen.de/robots.txt
HTTP/1.1 307 Temporary Redirect
Date: Thu, 06 Jul 2017 14:12:43 GMT
Server: Apache
Location: http://www.jh-moehringen.de/index.php?id=3&type=841133&type=841133
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
```

This is **not** from RealURL.

**Comment by thomaszbz** [comment] 2017-07-06 15:23
TYPO3 core generates 307 redirects, e.g. at https://github.com/TYPO3/TYPO3.CMS/blob/f8f0acbdd83631226bf7143e54318f9382d69267/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L2865

@dmitryd To file a bug report against typo3 core, could you please look up the core function realurl calls to pass over to TYPO3 core?

**Comment by dmitryd** [comment] 2017-07-06 15:55
@thomaszbz 

RealURL does not call the core. It is the other way: TYPO3 core calls RealURL [here](https://github.com/TYPO3/TYPO3.CMS/blob/f8f0acbdd83631226bf7143e54318f9382d69267/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L1040). Inside this call RealURL parses the URL and sets `$_GET['id']` and other query string parameters.

The function you found is most likely responsible. It sets the `type` argument explicitly but it also uses `addQueryString` without excluding `type`. So `type` argument will appear twice in the URL.

**Comment by thomaszbz** [comment] 2017-07-06 17:15
I filed an [issue](https://forge.typo3.org/issues/81815) against TYPO3 core.

**Comment by dmitryd** [comment] 2017-07-07 11:16
Closing because not related to RealURL.

**Closed by dmitryd** 2017-07-07 11:16 UTC
Labels: needs feedback
