### ISSUE TITLE
Reason: Cannot decode "news/detail/article/lorem-ipsum" (any GETvar)

### ISSUE THREAD

**Issue by bernhardberger** [dmitryd/typo3-realurl#188] opened 2016-07-01 11:10 UTC
With the fix for #186 (commit: https://github.com/dmitryd/typo3-realurl/commit/433d40b096f4002d2c1dacef2d7b94a9f228bfeb) there seems to have surfaced a new bug:

Reason: Cannot decode "news/detail/article/lorem-ipsum"

**This is reproducable in mutlilanguage environments** (not tested yet on a single lang install).

This extends to any GETvar configured in the 'postVarSets' array (this is NOT an isolated news issue) and produces the same error every single time.

**Comment by dmitryd** [comment] 2016-07-01 11:19
Interesting because that fix only affects how entries are put (or not put) to the cache. It does not affect decoding because it is executed after the decoding is finished...

**Comment by bernhardberger** [comment] 2016-07-01 11:25
Agreed. It may very well be just a side effect of the problem before being solved (I only managed to track the last bug down that fast as I got a PHP warning at that point and TYPO3 died with an Exception), so in production configuration it basically just skipped caching/cached wrong paths before the last bug was fixed)

**Comment by dmitryd** [comment] 2016-07-01 11:27
It appears that it cannot decode "news". Could be item 3 [here](https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#limitations)?

**Comment by bernhardberger** [comment] 2016-07-01 11:29
Unfotunately not.

The Sysfolder has a different name and is not within the same parent page or tree level either.

This also extends to ANY 'postVarSets', not only for news in this case.

**Comment by dmitryd** [comment] 2016-07-01 11:33
Do you have "news" as a postVar and also "News" as a page?

**Comment by bernhardberger** [comment] 2016-07-01 11:34
nope. postVar = 'article' and there is no page named 'article', not in default language or localized.

As I said.. this extends to any postVar, 'search', 'myplugin-123', 'article', etc.

**Comment by bernhardberger** [comment] 2016-07-01 11:35
In UrlDecoder:515 -> $result is still empty, as is $savedResult.

**Comment by dmitryd** [comment] 2016-07-01 11:38
It should not be anything related to postVars because this error is [thrown before](https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Decoder/UrlDecoder.php#L522) posVar decoding starts. It means that the path cannot be decoded.

Have you tried clearing both URL and path caches completely?

**Comment by bernhardberger** [comment] 2016-07-01 11:40
Yep. Cleaned all the tx_realurl tables.

So this pretty much means that it fails decoding the pagePath? Strange thing is: this only happens when postVars are in the URL I'm trying to access.. no problem at all navigating the sites without postvars..

**Comment by bernhardberger** [comment] 2016-07-01 11:48
Okay.. I just commented out the line throwing the exception.. -> now I get the following error:

> Reason: Segment "ueber-uns" was not a keyword for a postVarSet as expected on page with id=0.

(path is "ueber-uns/news/detail/article/lorem-ipsum..")

**Comment by dmitryd** [comment] 2016-07-01 11:50
Well, "just commenting" is not the right thing to do. RealURL is not a nuclear reactor, of course, but still requires knowledge of internal workings or it will break :)

**Comment by bernhardberger** [comment] 2016-07-01 11:59
..btw. it resolves correctly up to:
de/ueber-uns/news/detail/ (I can correctly call that page)
but as soon as a postVarSet is set it goes bad
de/ueber-uns/news/detail/article -> already get a can not decode exception

**Comment by dmitryd** [comment] 2016-07-01 12:05
I know what causes it I think...

**Comment by bernhardberger** [comment] 2016-07-01 12:06
Yeah me too..

`
} else {
						if ((int)$currentPid !== (int)$this->rootPageId) {
							$currentPid = 0;
//							$result = null;
						}
						array_unshift($remainingPathSegments, $segment);
						break;
					}`

**Comment by dmitryd** [comment] 2016-07-01 12:06
Not just that.

**Comment by bernhardberger** [comment] 2016-07-01 12:10
I'd be happy to dig into it if you could give me some hints where to look / what goes wrong.. I just struggle a bit to get the logic/call order behind it without being able to step through the code with a debugger..

**Comment by dmitryd** [comment] 2016-07-01 12:21
Does it help? (The issue is closed by github, not be me).

**Closed** 2016-07-01 12:20 UTC

**Comment by bernhardberger** [comment] 2016-07-01 12:24
Works like a charm! Thank you very much for digging into this so quickly!
