### ISSUE TITLE
Link generation in a scheduler task

### ISSUE THREAD

**Issue by Kephson** [dmitryd/typo3-realurl#105] opened 2016-03-30 13:59 UTC
Thanks again for your new version of realurl.

I'm generating links to frontend pages in some scheduler tasks.
An example for generation could be found in https://github.com/Kephson/reint_mailtask_example.

With realurl 1.x it works as expected and speaking links will be generated.
With realrul 2.x it doesn't work because in /Classes/Encoder/UrlEncoder.php the function isBackendMode() returns true (TYPO3_MODE == 'BE').

Is there some workaround how I could do this?

**Comment by dmitryd** [comment] 2016-03-30 15:31
Duplicate of #90.

Please, note that questions are not answered in the bug tracker. Use TYPO3 mailing lists to ask questions.

**Closed by dmitryd** 2016-03-30 15:31 UTC
Labels: duplicate
