### ISSUE TITLE
404

### ISSUE THREAD

**Issue by infabo** [dmitryd/typo3-realurl#489] opened 2017-06-06 07:34 UTC
Once this situation occurs (entries with cHash in the "speaking urls" module:

![grafik](https://cloud.githubusercontent.com/assets/3999104/26818430/e88ca684-4a9a-11e7-9311-9bdf71c6df8c.png)

You always get to a 404-page.

Once you delete the entries containing the cHash or flush the entries of the page, it returns to this state:

![grafik](https://cloud.githubusercontent.com/assets/3999104/26818484/19c9ef18-4a9b-11e7-9a74-70167b12e3f9.png)

And working again.

I have no idea when/why/how this can be reproduced.
Once cleaned the URL cache, it occurs again after 1-2 days in most cases.

I can't say since which exact version this bug exists, occurs since switching to 2.x.
2.1.0 not working, won't test on 2.1.1 because of #480.

**Comment by runepiper** [comment] 2017-06-07 11:38
I can confirm this behavior.

**Comment by echavaillaz** [comment] 2017-06-07 11:48
Me too...

**Comment by infabo** [comment] 2017-06-08 07:11
I guess we need more confirmation-power...

**Comment by ludovichemmerch** [comment] 2017-06-08 07:44
Same bug here.

I have this in my DB:
![image](https://user-images.githubusercontent.com/22192075/26917510-d47edd02-4c2e-11e7-8c8d-4798caf6f052.png)

The link for this page is generated without the slash => bug. If I add a final slash it works just fine.

**Comment by dmitryd** [comment] 2017-06-14 12:51
Please, see "Getting help" on the wiki. This was explained many times in help channels. Closing because not a bug of realurl...

**Closed by dmitryd** 2017-06-14 12:51 UTC

**Comment by infabo** [comment] 2017-06-14 19:45
Please provide me a link to the article - cant find it. Thank you.

**Comment by runepiper** [comment] 2017-06-15 06:24
@infabo I guess it's [Getting Help](https://github.com/dmitryd/typo3-realurl/wiki/Getting-help)

**Comment by infabo** [comment] 2017-06-16 07:46
![image](https://user-images.githubusercontent.com/3999104/27217076-a7e464e2-5278-11e7-8a90-793067620fcd.png)

**Comment by infabo** [comment] 2017-06-16 08:01
@dmitryd Instead of your typical RTFM-or-insert-some-coin answers (do you actually have a macro for this?), you just could have put your effort in an more helpful answer - so it could be used for reference. Searching for the problem in the Slack channel, reveals this pattern.

https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Developers#i-do-not-like-your-answers-they-are-rude

Actually, your answers are not rude. They are definitely not "simple and exact". Your answers just say in capital letters: "I don't give a fuck". I would appreciate such an answer - because that would be honest.

**Comment by infabo** [comment] 2017-06-20 13:57
https://github.com/dmitryd/typo3-realurl/issues/315

**Comment by dmitryd** [comment] 2017-06-21 14:42
@infabo is banned from this project.
