### ISSUE TITLE
 #1453732574: RealURL was not able to find the root page id for the domain

### ISSUE THREAD

**Issue by kludikovsky** [dmitryd/typo3-realurl#98] opened 2016-03-23 06:15 UTC
Have the same issue as [in this report](https://github.com/dmitryd/typo3-realurl/issues/61)
with a T3 7.6.4.and Realurl 2.0.10 (this is a new entry as the above mentioned is already closed)

What happend: 

- Had  a problem with Realurl (maybe since last update on 11.3.)
- updated again
- got error
- found this issue
- check the for the config file, but could not find one.
- re-executed the setup proc with the standard settings
  - means with 
    - Enable automatic configuration
    - basic.enableAutoConf
- Result: 
  - there is no config file in typo3conf

[EDIT]]

I have now tried to create my own config file (attached renamed to .txt
[KLRealUrlConfig.txt](https://github.com/dmitryd/typo3-realurl/files/184725/KLRealUrlConfig.txt)
) 
 and changed the setup to (as per config list)
`realurl = a:6:{s:10:"configFile";s:29:"typo3conf/KLRealUrlConfig.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"1";s:17:"enableBadBehavior";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}`

When I check the CONFIG there is no entry under EXTCONF for realurl!
[_screen_shot_2016-03-22_193748](https://cloud.githubusercontent.com/assets/6077916/13963498/e9a6ac6c-f065-11e5-9e4e-bea31acc424f.jpg)

**Comment by dmitryd** [comment] 2016-03-23 06:25
```
...LS['$TYPO3_CONF_VARS']['EX...
```

Do you see the error?

**Comment by kludikovsky** [comment] 2016-03-23 07:53
Thanks. Now it works.

Then there is the issue left that the Autoconfig das not work.
I did the config never before, alsways used the automatic one.

**Comment by dmitryd** [comment] 2016-03-23 21:39
It does not work because it is disabled:
`"enableAutoConf";s:1:"0"`

**Comment by Tuurlijk** [comment] 2016-03-25 08:38
Confirmed.

The issue can be inspected in the 6.2.19 site of the TypoTry package: https://github.com/Tuurlijk/TYPOTry

The realurl setup is the same for all sites in the box: 6.2.19, 7.6.4 and 8.0.0

On 7.6 and 8.0 it works. 

This error occurs only for the 6.2 installation:

![screen shot 2016-03-25 at 09 30 44](https://cloud.githubusercontent.com/assets/790979/14040978/0e883182-f26d-11e5-8a3a-dcdce1ad0da0.png)

**Comment by dmitryd** [comment] 2016-03-26 09:13
@Tuurlijk Are you sure you use `$GLOBALS['TYPO3_CONF_VARS']` and not `$TYPO3_CONF_VARS` in your config file?

**Comment by dmitryd** [comment] 2016-03-26 09:24
@kludikovsky 
> Then there is the issue left that the Autoconfig das not work.

Autoconfig does not work if:
* you have a manual configuration file (you wrote you have)
* it is disabled (it is disabled in your config)

**Comment by dmitryd** [comment] 2016-03-26 09:30
@Tuurlijk Another thing. Does your installation meet [realurl requirements](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-root-pages-for-realurl)?

**Comment by soee** [comment] 2016-03-27 10:01
I'm not sure why by this error on the screenshot can be 'fixed'  by removing the casting part in line 207 of realurl/Classes/EncodeDecoderBase.php:

so this won't work:
`$this->rootPageId = (int)$this->configuration->get('pagePath/rootpage_id');`

tis works:
`$this->rootPageId = $this->configuration->get('pagePath/rootpage_id');`

I'm on PHP7 here.

**Comment by dmitryd** [comment] 2016-03-27 15:43
> I'm not sure why by this error on the screenshot can be 'fixed' by removing the casting part in line 207 of realurl/Classes/EncodeDecoderBase.php:

No, it cannot because `rootpage_id` must be an integer number. This cast will not affect it if it is an integer already (as it should be).

**Comment by kludikovsky** [comment] 2016-03-27 18:00
I have now retested the configuration 
- deleted the manual configuration entry in the update tool and
- set the autoconfig

It did not create a config file in typo3conf

**Comment by Tuurlijk** [comment] 2016-03-27 20:38
Yes, it meets the requirements. It has the root page marked as 'root page'.

I have prepared a test environment for you here: https://github.com/Tuurlijk/TYPOTry Please fire up the box and see for yourself.

**Comment by dmitryd** [comment] 2016-03-30 15:35
I am on it. No forecast for fixing because I have limited time at the moment. As soon as I find the reason for the issue, I will fix ASAP.

I hope the box has XDebug...

**Comment by dmitryd** [comment] 2016-03-30 16:18
@Tuurlijk In case of your box the problem is in the `BK2K\BootstrapPackage\Hooks\RealUrl\AutoConfig->addConfigVersion2x`. See #53.

**Closed** 2016-03-30 18:19 UTC
