### ISSUE TITLE
[BUG] Exception thrown if $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'] is not initialized

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [dmitryd/typo3-realurl#504] opened 2017-07-11 15:51 UTC
Since 8cfb6f02 EXT:realurl causes an exception when installing TYPO3 CMS/flushing caches using TYPO3 Console.

> [Sub-process exception: TYPO3\CMS\Core\Error\Exception ]
 #1: Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/typo3conf/ext/realurl/ext_localconf.php line 74
 thrown in file Classes/Error/ErrorHandler.php
 in line 68

Looks as if `$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters']` is not initialized at that moment.

**Comment by dmitryd** [comment] 2017-07-13 12:21
The fix is not exactly right. If the array does not exist, it should not be used, that's all.

**Comment by markuspoerschke** [comment] 2017-11-06 18:07
@dmitryd I added this change here: #559 

If change in #559 is fine, we can close this Merge Request.

**Comment by tbal** [comment] 2017-12-07 10:34
A possible workaround till this bug is fixed in realurl is to initialize the array in LocalConfiguration.php :
```
    ...
    'FE' => [
        ...
        'cacheHash' => [
            'excludedParameters' => []
        ],
        ...
    ],
    ...
```

**Comment by dmitryd** [comment] 2017-12-07 12:03
This will never be "fixed" in RealURL because it is not a bug. Any configuration should be done only after TYPO3 is initialized. And TYPO3 has this option set already, so RealURL will not set it again.

See: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Configuration/DefaultConfiguration.php#L1034

**Closed by dmitryd** 2017-12-07 12:03 UTC

**Comment by markuspoerschke** [comment] 2018-01-03 09:36
@dmitryd For TYPO3 Version 7.6 this value is not present yet. Therefore this fix is only needed if TYPO3 <8 is used. Can you check #559?
